# 基于官方的基础镜像，例如Ubuntu
FROM ubuntu:latest

# 设置工作目录
WORKDIR /usr/src/app

# 构建IPFS
COPY envs/ipfs ./envs/ipfs
COPY .build/ipfs ./envs/ipfs/bin/ipfs

# 构建Geth
COPY envs/mychain ./envs/mychain
COPY .build/geth ./envs/mychain/bin/geth

# 初始化
COPY ./start_env.sh .
RUN mkdir ./envs/logs
RUN mkdir ./tmp
RUN ./start_env.sh init

# 定义容器启动时执行的命令
CMD ["./start_env.sh", "up"]