app:
  # 【日志记录类型】：server、file、console
  logtype: console
  # 【日志文件的路径】：logtype为file时生效
  logpath:
  # 【日志服务器】：用服务器收集各节点的日志（暂未实现）
  logserver: 127.0.0.1:1234
  # 【日志级别】：debug、info、error
  loglevel: info
  # 【IPFS服务url】：本地私有部署IPFS
  ipfs_url: /ip4/127.0.0.1/tcp/5001
  # 【web3服务url】：HTTP接口地址
  web3_url: http://127.0.0.1:8545
  # 测试账户地址
  account_path: "config/bc_keys.json"

# 实验时用于控制系统的的客户端
client:
  # 【服务端口】：用于实验时获取数据的服务端口
  serving_port: 33333

requester:
  # 【任务获取端口】：提供子任务获取的端口
  task_pull_port: 10000
  # 【服务端口】：用于实验时获取数据的服务端口
  serving_port: 20000

randomizer:
  # 【ZKP验证端口】：提供ZKP交互式验证的端口
  proving_server_port_base: 11000
  # 【服务端口】：用于实验时获取数据的服务端口
  serving_port_base: 13000

submitter:
  # 【服务端口】：用于实验时获取数据的服务端口
  serving_port_base: 14000

smart_contract:
  # 【合约地址】：系统中使用的合约地址（本地部署）
  address: "0xBC653A8d353F7D93844e5d94BD99aC93f4Ef588B"
  # 【合约ABI文件位置】：本地硬盘中的位置，以项目根目录为基准
  abi_path: "solidity/CrowdsourcingContract.json"
  # 【监听合约事件的拉取频率】：秒
  poll_interval: 1